pipeline {
    agent {
        docker { image 'maven:3.8.1-openjdk-11' }
        reuseNode true
    }
    stages {
        stage('showVersion') {
            steps {
                sh 'mvn --version'
            }

        }

    }


}